#!/bin/bash

arg="$1"

function checkExit() {
    if [ "$?" = 0 ]; then
        exit 0
    else
        exit 1
    fi
}

if [ "$arg" = "0" ] && pass > /dev/null; then
    echo "$(pass show sshpasswords/andrew)"
    checkExit
else
    exit 1
fi
