#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
EXPECT="password:"

sshcommand="/usr/bin/mosh"
if [ ! -f "$sshcommand" ]; then
    sshcommand="ssh"
fi

sshhost="$($DIR/gethost "${@: -1}")"

passwordIndex="$?"
password=""

if [ "$passwordIndex" != "0" ]; then
    password="$($DIR/getpassword $(($passwordIndex-1)))"
    code="$?"

    if [ "$code" != "0" ]; then
        echo -e "\e[31m Could not get password \"sshpasswords\" from \"pass\" password manager.\e[m"
    fi
fi

num=$#
commandargs="${@:1:$((num-1))}"

function run {
    if [ "$passwordIndex" != "0" ] && [ "$password" != "" ] && sshpass > /dev/null;
    then
        sshpass -p "$password" "$1" $commandargs "$sshhost"
    else
        if [ "$commandargs" == "" ]; then
            "$1" "$sshhost"
        else
            "$1" "$commandargs" "$sshhost"
        fi
    fi
}

run $sshcommand
if [ "$?" == "10" ]; then
    run "/usr/bin/ssh"
fi
