FROM ubuntu:18.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y vim git python3-pip nodejs tmux rlwrap npm

RUN git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

RUN git clone https://github.com/stevenshan/configurations.git ~/configurations
RUN cp ~/configurations/dotfiles/.* ~/ | true
RUN vim +PluginInstall +qall

RUN mkdir -p ~/.ssh
RUN cp ~/configurations/config ~/.ssh | true
RUN chmod 600 ~/.ssh/config | true

RUN git config --global user.email "me@stevenshan.com" && \
    git config --global user.name "Steven Shan"

CMD /bin/bash
